# Generated by Django 3.2.13 on 2022-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=30)),
                ('email_costumer', models.CharField(max_length=30)),
                ('phone_costumer', models.CharField(max_length=30)),
                ('decription', models.CharField(max_length=30)),
            ],
        ),
    ]
